// Majors data parsed from CSV
export interface Major {
  code: string;
  name: string;
  category: string;
}

export const majorsData: Major[] = [
  { code: "1100", name: "General Agriculture", category: "Agriculture & Natural Resources" },
  { code: "1101", name: "Agriculture Production And Management", category: "Agriculture & Natural Resources" },
  { code: "1102", name: "Agricultural Economics", category: "Agriculture & Natural Resources" },
  { code: "1103", name: "Animal Sciences", category: "Agriculture & Natural Resources" },
  { code: "1104", name: "Food Science", category: "Agriculture & Natural Resources" },
  { code: "1105", name: "Plant Science And Agronomy", category: "Agriculture & Natural Resources" },
  { code: "1106", name: "Soil Science", category: "Agriculture & Natural Resources" },
  { code: "1199", name: "Miscellaneous Agriculture", category: "Agriculture & Natural Resources" },
  { code: "1302", name: "Forestry", category: "Agriculture & Natural Resources" },
  { code: "1303", name: "Natural Resources Management", category: "Agriculture & Natural Resources" },
  { code: "6000", name: "Fine Arts", category: "Arts" },
  { code: "6001", name: "Drama And Theater Arts", category: "Arts" },
  { code: "6002", name: "Music", category: "Arts" },
  { code: "6003", name: "Visual And Performing Arts", category: "Arts" },
  { code: "6004", name: "Commercial Art And Graphic Design", category: "Arts" },
  { code: "6005", name: "Film Video And Photographic Arts", category: "Arts" },
  { code: "6007", name: "Studio Arts", category: "Arts" },
  { code: "6099", name: "Miscellaneous Fine Arts", category: "Arts" },
  { code: "1301", name: "Environmental Science", category: "Biology & Life Science" },
  { code: "3600", name: "Biology", category: "Biology & Life Science" },
  { code: "3601", name: "Biochemical Sciences", category: "Biology & Life Science" },
  { code: "3602", name: "Botany", category: "Biology & Life Science" },
  { code: "3603", name: "Molecular Biology", category: "Biology & Life Science" },
  { code: "3604", name: "Ecology", category: "Biology & Life Science" },
  { code: "3605", name: "Genetics", category: "Biology & Life Science" },
  { code: "3606", name: "Microbiology", category: "Biology & Life Science" },
  { code: "3607", name: "Pharmacology", category: "Biology & Life Science" },
  { code: "3608", name: "Physiology", category: "Biology & Life Science" },
  { code: "3609", name: "Zoology", category: "Biology & Life Science" },
  { code: "3611", name: "Neuroscience", category: "Biology & Life Science" },
  { code: "3699", name: "Miscellaneous Biology", category: "Biology & Life Science" },
  { code: "4006", name: "Cognitive Science And Biopsychology", category: "Biology & Life Science" },
  { code: "6200", name: "General Business", category: "Business" },
  { code: "6201", name: "Accounting", category: "Business" },
  { code: "6202", name: "Actuarial Science", category: "Business" },
  { code: "6203", name: "Business Management And Administration", category: "Business" },
  { code: "6204", name: "Operations Logistics And E-Commerce", category: "Business" },
  { code: "6205", name: "Business Economics", category: "Business" },
  { code: "6206", name: "Marketing And Marketing Research", category: "Business" },
  { code: "6207", name: "Finance", category: "Business" },
  { code: "6209", name: "Human Resources And Personnel Management", category: "Business" },
  { code: "6210", name: "International Business", category: "Business" },
  { code: "6211", name: "Hospitality Management", category: "Business" },
  { code: "6212", name: "Management Information Systems And Statistics", category: "Business" },
  { code: "6299", name: "Miscellaneous Business & Medical Administration", category: "Business" },
  { code: "1901", name: "Communications", category: "Communications & Journalism" },
  { code: "1902", name: "Journalism", category: "Communications & Journalism" },
  { code: "1903", name: "Mass Media", category: "Communications & Journalism" },
  { code: "1904", name: "Advertising And Public Relations", category: "Communications & Journalism" },
  { code: "2001", name: "Communication Technologies", category: "Computers & Mathematics" },
  { code: "2100", name: "Computer And Information Systems", category: "Computers & Mathematics" },
  { code: "2101", name: "Computer Programming And Data Processing", category: "Computers & Mathematics" },
  { code: "2102", name: "Computer Science", category: "Computers & Mathematics" },
  { code: "2105", name: "Information Sciences", category: "Computers & Mathematics" },
  { code: "2106", name: "Computer Administration Management And Security", category: "Computers & Mathematics" },
  { code: "2107", name: "Computer Networking And Telecommunications", category: "Computers & Mathematics" },
  { code: "3700", name: "Mathematics", category: "Computers & Mathematics" },
  { code: "3701", name: "Applied Mathematics", category: "Computers & Mathematics" },
  { code: "3702", name: "Statistics And Decision Science", category: "Computers & Mathematics" },
  { code: "4005", name: "Mathematics And Computer Science", category: "Computers & Mathematics" },
  { code: "2300", name: "General Education", category: "Education" },
  { code: "2301", name: "Educational Administration And Supervision", category: "Education" },
  { code: "2303", name: "School Student Counseling", category: "Education" },
  { code: "2304", name: "Elementary Education", category: "Education" },
  { code: "2305", name: "Mathematics Teacher Education", category: "Education" },
  { code: "2306", name: "Physical And Health Education Teaching", category: "Education" },
  { code: "2307", name: "Early Childhood Education", category: "Education" },
  { code: "2308", name: "Science And Computer Teacher Education", category: "Education" },
  { code: "2309", name: "Secondary Teacher Education", category: "Education" },
  { code: "2310", name: "Special Needs Education", category: "Education" },
  { code: "2311", name: "Social Science Or History Teacher Education", category: "Education" },
  { code: "2312", name: "Teacher Education: Multiple Levels", category: "Education" },
  { code: "2313", name: "Language And Drama Education", category: "Education" },
  { code: "2314", name: "Art And Music Education", category: "Education" },
  { code: "2399", name: "Miscellaneous Education", category: "Education" },
  { code: "3501", name: "Library Science", category: "Education" },
  { code: "1401", name: "Architecture", category: "Engineering" },
  { code: "2400", name: "General Engineering", category: "Engineering" },
  { code: "2401", name: "Aerospace Engineering", category: "Engineering" },
  { code: "2402", name: "Biological Engineering", category: "Engineering" },
  { code: "2403", name: "Architectural Engineering", category: "Engineering" },
  { code: "2404", name: "Biomedical Engineering", category: "Engineering" },
  { code: "2405", name: "Chemical Engineering", category: "Engineering" },
  { code: "2406", name: "Civil Engineering", category: "Engineering" },
  { code: "2407", name: "Computer Engineering", category: "Engineering" },
  { code: "2408", name: "Electrical Engineering", category: "Engineering" },
  { code: "2409", name: "Engineering Mechanics Physics And Science", category: "Engineering" },
  { code: "2410", name: "Environmental Engineering", category: "Engineering" },
  { code: "2411", name: "Geological And Geophysical Engineering", category: "Engineering" },
  { code: "2412", name: "Industrial And Manufacturing Engineering", category: "Engineering" },
  { code: "2413", name: "Materials Engineering And Materials Science", category: "Engineering" },
  { code: "2414", name: "Mechanical Engineering", category: "Engineering" },
  { code: "2415", name: "Metallurgical Engineering", category: "Engineering" },
  { code: "2416", name: "Mining And Mineral Engineering", category: "Engineering" },
  { code: "2417", name: "Naval Architecture And Marine Engineering", category: "Engineering" },
  { code: "2418", name: "Nuclear Engineering", category: "Engineering" },
  { code: "2419", name: "Petroleum Engineering", category: "Engineering" },
  { code: "2499", name: "Miscellaneous Engineering", category: "Engineering" },
  { code: "2500", name: "Engineering Technologies", category: "Engineering" },
  { code: "2501", name: "Engineering And Industrial Management", category: "Engineering" },
  { code: "2502", name: "Electrical Engineering Technology", category: "Engineering" },
  { code: "2503", name: "Industrial Production Technologies", category: "Engineering" },
  { code: "2504", name: "Mechanical Engineering Related Technologies", category: "Engineering" },
  { code: "2599", name: "Miscellaneous Engineering Technologies", category: "Engineering" },
  { code: "5008", name: "Materials Science", category: "Engineering" },
  { code: "4002", name: "Nutrition Sciences", category: "Health" },
  { code: "6100", name: "General Medical And Health Services", category: "Health" },
  { code: "6102", name: "Communication Disorders Sciences And Services", category: "Health" },
  { code: "6103", name: "Health And Medical Administrative Services", category: "Health" },
  { code: "6104", name: "Medical Assisting Services", category: "Health" },
  { code: "6105", name: "Medical Technologies Technicians", category: "Health" },
  { code: "6106", name: "Health And Medical Preparatory Programs", category: "Health" },
  { code: "6107", name: "Nursing", category: "Health" },
  { code: "6108", name: "Pharmacy Pharmaceutical Sciences And Administration", category: "Health" },
  { code: "6109", name: "Treatment Therapy Professions", category: "Health" },
  { code: "6110", name: "Community And Public Health", category: "Health" },
  { code: "6199", name: "Miscellaneous Health Medical Professions", category: "Health" },
  { code: "1501", name: "Area Ethnic And Civilization Studies", category: "Humanities & Liberal Arts" },
  { code: "2601", name: "Linguistics And Comparative Language And Literature", category: "Humanities & Liberal Arts" },
  { code: "2602", name: "French German Latin And Other Common Foreign Language Studies", category: "Humanities & Liberal Arts" },
  { code: "2603", name: "Other Foreign Languages", category: "Humanities & Liberal Arts" },
  { code: "3301", name: "English Language And Literature", category: "Humanities & Liberal Arts" },
  { code: "3302", name: "Composition And Rhetoric", category: "Humanities & Liberal Arts" },
  { code: "3401", name: "Liberal Arts", category: "Humanities & Liberal Arts" },
  { code: "3402", name: "Humanities", category: "Humanities & Liberal Arts" },
  { code: "4001", name: "Intercultural And International Studies", category: "Humanities & Liberal Arts" },
  { code: "4801", name: "Philosophy And Religious Studies", category: "Humanities & Liberal Arts" },
  { code: "4901", name: "Theology And Religious Vocations", category: "Humanities & Liberal Arts" },
  { code: "5502", name: "Anthropology And Archeology", category: "Humanities & Liberal Arts" },
  { code: "6006", name: "Art History And Criticism", category: "Humanities & Liberal Arts" },
  { code: "6402", name: "History", category: "Humanities & Liberal Arts" },
  { code: "6403", name: "United States History", category: "Humanities & Liberal Arts" },
  { code: "2201", name: "Cosmetology Services And Culinary Arts", category: "Industrial Arts & Consumer Services" },
  { code: "2901", name: "Family And Consumer Sciences", category: "Industrial Arts & Consumer Services" },
  { code: "3801", name: "Military Technologies", category: "Industrial Arts & Consumer Services" },
  { code: "4101", name: "Physical Fitness Parks Recreation And Leisure", category: "Industrial Arts & Consumer Services" },
  { code: "5601", name: "Construction Services", category: "Industrial Arts & Consumer Services" },
  { code: "5701", name: "Electrical And Mechanical Repairs", category: "Industrial Arts & Consumer Services" },
  { code: "5901", name: "Transportation Sciences And Technologies", category: "Industrial Arts & Consumer Services" },
  { code: "4000", name: "Multi/Interdisciplinary Studies", category: "Interdisciplinary" },
  { code: "3201", name: "Court Reporting", category: "Law & Public Policy" },
  { code: "3202", name: "Pre-Law And Legal Studies", category: "Law & Public Policy" },
  { code: "5301", name: "Criminal Justice And Fire Protection", category: "Law & Public Policy" },
  { code: "5401", name: "Public Administration", category: "Law & Public Policy" },
  { code: "5402", name: "Public Policy", category: "Law & Public Policy" },
  { code: "bbbb ", name: "N/A (Less Than Bachelor'S Degree)", category: "NA" },
  { code: "5000", name: "Physical Sciences", category: "Physical Sciences" },
  { code: "5001", name: "Astronomy And Astrophysics", category: "Physical Sciences" },
  { code: "5002", name: "Atmospheric Sciences And Meteorology", category: "Physical Sciences" },
  { code: "5003", name: "Chemistry", category: "Physical Sciences" },
  { code: "5004", name: "Geology And Earth Science", category: "Physical Sciences" },
  { code: "5005", name: "Geosciences", category: "Physical Sciences" },
  { code: "5006", name: "Oceanography", category: "Physical Sciences" },
  { code: "5007", name: "Physics", category: "Physical Sciences" },
  { code: "5098", name: "Multi-Disciplinary Or General Science", category: "Physical Sciences" },
  { code: "5102", name: "Nuclear", category: " INDUSTRIAL RADIOLOGY" },
  { code: "5200", name: "Psychology", category: "Psychology & Social Work" },
  { code: "5201", name: "Educational Psychology", category: "Psychology & Social Work" },
  { code: "5202", name: "Clinical Psychology", category: "Psychology & Social Work" },
  { code: "5203", name: "Counseling Psychology", category: "Psychology & Social Work" },
  { code: "5205", name: "Industrial And Organizational Psychology", category: "Psychology & Social Work" },
  { code: "5206", name: "Social Psychology", category: "Psychology & Social Work" },
  { code: "5299", name: "Miscellaneous Psychology", category: "Psychology & Social Work" },
  { code: "5403", name: "Human Services And Community Organization", category: "Psychology & Social Work" },
  { code: "5404", name: "Social Work", category: "Psychology & Social Work" },
  { code: "4007", name: "Interdisciplinary Social Sciences", category: "Social Science" },
  { code: "5500", name: "General Social Sciences", category: "Social Science" },
  { code: "5501", name: "Economics", category: "Social Science" },
  { code: "5503", name: "Criminology", category: "Social Science" },
  { code: "5504", name: "Geography", category: "Social Science" },
  { code: "5505", name: "International Relations", category: "Social Science" },
  { code: "5506", name: "Political Science And Government", category: "Social Science" },
  { code: "5507", name: "Sociology", category: "Social Science" },
  { code: "5599", name: "Miscellaneous Social Sciences", category: "Social Science" },
];

// Search majors by name
export function searchMajors(query: string): Major[] {
  if (!query || query.length < 2) return [];

  const lowerQuery = query.toLowerCase();
  return majorsData.filter(major =>
    major.name.toLowerCase().includes(lowerQuery)
  ).slice(0, 5); // Return max 5 results
}
